export {default as Header} from "./Header/header.jsx" 
export {default as Blog} from "./Blog/blog.jsx" 
// export {default as CartSlide} from "./CartSlide/cartslide.jsx" 
export {default as NewArrival} from "./New Arrival/newArrival.jsx" 
export {default as NewsLetter} from "./NewsLetter/newsletter.jsx" 
export {default as SpecialOffer} from "./Special-Offer/specialoffer.jsx" 
export {default as Footer} from "./Footer/footer.jsx" 
